/**
 * Parse installed aliases from file (deprecated — kept for reference)
 *
 * The old system (aliases/index.sh with markers) has been replaced by
 * a per-file structure under ~/.pocket/alias-list/.
 *
 * This file remains for reference only; it is no longer imported.
 */

export const MARKER_START = `# ====== pocket:start ======

# Generated by @legend80s/pocket (https://www.npmjs.com/package/@legend80s/pocket)
# Modify as you wish — you own the code, just like shadcn.`

export const MARKER_END = "# ====== pocket:end ======"

/**
 * @deprecated Use filesystem check under aliasDir instead.
 */
/** @param {string} source */
export function extractDescription(source) {
  const match = source.match(/^# desc:\s*(.+)/m)
  return match ? match[1] : ""
}
